"""
gm_base.py - the game master. GIVEN. You do not edit this file.

Two game masters, same world, same rules, same model:

    GameMaster(memory=True)    yours. Preferences always loaded, facts recalled per
                               turn and cited, tonight's summary + recent turns.
                               After each reply: extract -> remember -> add -> fold?
    GameMaster(memory=False)   the goldfish. Plain growing history. Knows the world
                               canon and nothing about this party.

Every reply reports the prompt size as billed. That number is the receipt.
"""

from __future__ import annotations

import datetime as dt
import importlib
import re
import sys
from pathlib import Path

from common import HERE, chat, say

memory = sys.modules.get("campaign_memory") or importlib.import_module("campaign_memory")

WORLD = (HERE / "world" / "WORLD.md").read_text(encoding="utf-8")

RULES = """
You are the game master of a cosy, low-stakes fantasy tabletop game set in the Hollow.
- Reply in at most 90 words. Narrate, then end with what the player can do or a question.
- Never kill or harm the player's character. Follow the player's stated tone and name preferences exactly.
- The WORLD text is how things stood when the party FIRST arrived. Anything under REMEMBERED FACTS or
  in the SUMMARY overrides it: if a remembered fact says an NPC died or a bridge burned, that is now true.
- When the player DECLARES something ("I take the amulet", "Marra is dead"), it is true. Confirm it, do not argue.
- When a REMEMBERED FACT shapes your reply, append its citation exactly as given, in parentheses.
- REMEMBERED FACTS name people; the WORLD text says who they are. "The miller" is Old Tobb, "the smith" is
  Marra, "the herbalist" is Mirra - connect roles to names before deciding you do not recall.
- Every REMEMBERED FACT carries its night and date. When facts differ or the player says "last time",
  the most recent one wins; when they agree, the oldest was established first.
- Answer from REMEMBERED FACTS even when their wording differs from the question ("swore to find out who started
  the fire" answers "what did Dax swear to do"). Only say you do not recall when NOTHING remembered bears on it.
  Never invent a past event, item or promise.
"""


class GameMaster:
    def __init__(self, use_memory: bool, asof: dt.date, night: int, ltm=None, stm=None):
        self.use_memory = use_memory
        self.asof = asof
        self.night = night
        self.ltm = ltm
        self.stm = stm
        self.history: list[tuple[str, str]] = []     # goldfish only
        self.max_prompt = 0
        self.area = 0
        self.turns = 0
        self.facts_stored = 0

    # ------------------------------------------------------------------ #
    def respond(self, player_text: str, record: bool = True) -> dict:
        messages: list[tuple[str, str]] = [("system", WORLD.strip() + "\n\nRULES:" + RULES)]
        recalled: list[dict] = []

        if self.use_memory:
            prefs = self.ltm.preferences()
            if prefs:
                messages.append(("system", "PLAYER PREFERENCES (always apply):\n" +
                                 "\n".join(f"- {p['subject']}: {p['text']}" for p in prefs)))
            recalled = self.ltm.recall(player_text, self.asof, k=6)
            if recalled:
                messages.append(("system", "REMEMBERED FACTS (from earlier game nights; cite when used):\n" +
                                 "\n".join(f"- [{h['type']}] {h['subject']}: {h['text']}  {memory.cite(h)}"
                                           for h in recalled)))
            messages += self.stm.context()
        else:
            messages += self.history

        messages.append(("user", player_text))
        text, ptoks = chat(messages, temperature=0.6)

        if record:
            self.turns += 1
            self.max_prompt = max(self.max_prompt, ptoks)
            self.area += ptoks
            if self.use_memory:
                facts = self.ltm.extract(player_text, text)
                self.facts_stored += self.ltm.remember(facts, self.asof, self.night)
                self.stm.add("user", player_text)
                self.stm.add("assistant", text)
                if self.stm.should_fold():
                    self.stm.fold()
            else:
                self.history += [("user", player_text), ("assistant", text)]
        return {"text": text, "prompt_tokens": ptoks, "recalled": recalled}


# ---------------------------------------------------------------------- quiz --
def _hits(answer: str, words: list[str]) -> bool:
    a = answer.lower()
    return any(re.search(rf"\b{re.escape(w.lower())}\b", a) for w in words)


def run_quiz(gm: GameMaster, quiz: dict) -> tuple[int, list[dict]]:
    """Ask the questions as the player, before tonight's play. record=False: the quiz
    must not itself become memory. Graded by word match against the accepted answers."""
    rows, score = [], 0
    for q in quiz["questions"]:
        r = gm.respond(q["q"], record=False)
        ok = _hits(r["text"], q["accept"]) and not _hits(r["text"], q.get("reject", []))
        score += int(ok)
        rows.append({"q": q["q"], "answer": r["text"], "ok": ok, "prompt_tokens": r["prompt_tokens"]})
        say(f"    {'ok  ' if ok else 'MISS'}  {q['q']}\n          -> {r['text'][:140]}")
    return score, rows
